# Generated by Django 5.2.1 on 2025-05-30 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacanciesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='author',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='employment',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='region',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='skills',
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('salary_from', models.IntegerField(blank=True, null=True)),
                ('salary_to', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacanciesapp.employer')),
            ],
        ),
        migrations.DeleteModel(
            name='Employers',
        ),
        migrations.DeleteModel(
            name='Vacancies',
        ),
    ]
